# main.py
# to use MCP Remote MCP server for tavily
# comment "from tools.tavily_tool import tavily_search"
# in hotel agent function  we will comment: hotel_results = tavily_search(query) and add
#    hotel_results = asyncio.run(
#        tavily_mcp_search(query)   #this function implemeted in mcp_client.py
#    )


#inside langgraph, we create state, and that state is shared memory, all nodes of langgraph will take data from this memory and store in this memory, consider as common store
import os
from typing import TypedDict, Annotated
import operator
#----------------------------------------------
import asyncio

import psycopg #PostgreSQL driver for Python
# we need to create graph in langgraph so these packages required
from langgraph.graph import StateGraph, START, END
#-----------------------------------
#LangGraph component that uses PostgreSQL to save/checkpoint graph state (Memory)
from langgraph.checkpoint.postgres import PostgresSaver
#---------------------------------------------
#import different types of messages from LangChain so your Python code can represent conversations between the user, AI, and system.
from langchain_core.messages import (
    AnyMessage, #any of the below
    HumanMessage, #message from the user/human.
    AIMessage, #message generated by the AI/LLM
    SystemMessage, #Initial Promt given to the AI by system
)
#--------------------------------------------

# to use groq we need to use LLM 
from langchain_groq import ChatGroq
#--------------------------------------

# custom packages by created by us
#from tools.tavily_tool import tavily_search  #tavily_search  a function written in tavily_tool 
#from tools.flight_tool import search_flights #search_flights a function written in flight_tool 

#import all the tools created in mcp_client.py
from mcp_client import (
    tavily_mcp_search,
    get_airports,
    get_airlines,
    aviation_mcp_call,extract_destination,forecast_mcp_search,weather_mcp_search
)

# to use .env variables
from dotenv import load_dotenv
load_dotenv()
#------------------------

DATABASE_URL = os.getenv("DATABASE_URL")

# Groq LLM  using qwen/qwen3.6-27b model
llm = ChatGroq(
    model="qwen/qwen3.6-27b",
    temperature=0,
    max_tokens=900
)


# State (Shared Memory)
class TravelState(TypedDict):
    messages: Annotated[list[AnyMessage], operator.add]
    user_query: str
    flight_results: str
    hotel_results: str
    itinerary: str
    llm_calls: int
    weather_results: str

# # Flight Agent
# def flight_agent(state: TravelState):
#     query = state["user_query"]
#     flight_data = search_flights(query)
#     return {
#         "flight_results": flight_data,
#         "messages": [
#             AIMessage(content=f"Flight results fetched")
#         ],
#         "llm_calls": state.get("llm_calls", 0) + 1
#     }



# Flight Tool Router Prompt
FLIGHT_AGENT_PROMPT = """
You are a travel flight expert.

User Query:
{query}

Airport Information:
{airport_data}

Airline Information:
{airline_data}

Generate:

1. Likely departure airport
2. Likely arrival airport
3. Airlines serving this route
4. Typical flight duration
5. Estimated airfare range
6. Peak season pricing warning
7. Booking advice

Return concise travel guidance.
"""

# Flight Agent
def flight_agent(state: TravelState):
    print("\nINSIDE FLIGHT AGENT\n")

    query = state["user_query"]

    try:

        airports = asyncio.run(
            aviation_mcp_call(
                "list_airports"
            )
        )

        airlines = asyncio.run(
            aviation_mcp_call(
                "list_airlines"
            )
        )

        prompt = FLIGHT_AGENT_PROMPT.format(
            query=query,
            airport_data=str(airports)[:3000],
            airline_data=str(airlines)[:3000]
        )

        response = llm.invoke([
            SystemMessage(
                content="You are an expert travel flight planner."
            ),
            HumanMessage(content=prompt)
        ])

        flight_data = response.content

    except Exception as e:

        flight_data = f"Flight information unavailable: {str(e)}"

    return {
        "flight_results": flight_data,
        "messages": [
            AIMessage(
                content="Flight recommendations generated"
            )
        ],
        "llm_calls": state.get("llm_calls", 0) + 1
    }



# Hotel Agent
def hotel_agent(state: TravelState):
    query = f"Best hotels for {state['user_query']}"
    #hotel_results = tavily_search(query)
    hotel_results = asyncio.run(
        tavily_mcp_search(query)
    )
    return {
        "hotel_results": hotel_results,
        "messages": [
            AIMessage(content="Hotel information fetched")
        ],
        "llm_calls": state.get("llm_calls", 0) + 1
    }


def weather_agent(state: TravelState):

    city = extract_destination(state["user_query"])

    weather_data = asyncio.run(
        weather_mcp_search(city)
    )

    forecast_data = asyncio.run(
        forecast_mcp_search(city)
    )

    return {
        "weather_results": f"""
        Current Weather:
        {weather_data}

        Forecast:
        {forecast_data}
        """,
        "messages": [
            AIMessage(
                content="Weather information fetched"
            )
        ]
    }

# Itinerary Agent
def itinerary_agent(state: TravelState):

    prompt = f"""
    Create a travel itinerary.
    User Query:
    {state['user_query']}

    Flight Results:
    {state['flight_results']}

    Hotel Results:
    {state['hotel_results']}

    Weather Information:
    {state['weather_results']}
    """

    response = llm.invoke([
        SystemMessage(
            content="You are an expert travel planner"
        ),
        HumanMessage(content=prompt)
    ])

    return {
        "itinerary": response.content,
        "messages": [response],
        "llm_calls": state.get("llm_calls", 0) + 1
    }


#How LangGraph Works
#Create the graph — Define the overall workflow.
#Add nodes — Add functions/agents that perform specific tasks.
#Connect the nodes — Define how the workflow moves from one node to another.
#Define the state — Specify the information that flows through the graph.
#Compile the graph — Turn the graph definition into an executable workflow.
#Run the graph — Provide the initial input and execute the workflow.
#Get the output — Receive the final state/result after the workflow completes.

#step1: Create the graph
graph = StateGraph(TravelState)

#step2: Add Nodes
#graph.add_node("node name, "agent name")

graph.add_node("flight_agent", flight_agent)
graph.add_node("hotel_agent", hotel_agent)
graph.add_node("weather_agent", weather_agent)
graph.add_node("itinerary_agent", itinerary_agent)

#step3: Connect the nodes
graph.add_edge(START, "flight_agent")
graph.add_edge("flight_agent", "hotel_agent")
graph.add_edge("hotel_agent", "weather_agent")
graph.add_edge("weather_agent", "itinerary_agent")
graph.add_edge("itinerary_agent", END)

#step4: To use memory (store & get)
# Persistent connection so both CLI and Streamlit can share the compiled app
_conn = psycopg.connect(DATABASE_URL,autocommit=True)
checkpointer = PostgresSaver(_conn)
checkpointer.setup()

#step5: Compile the graph
app = graph.compile(checkpointer=checkpointer)


if __name__ == "__main__":
#if you wanted to store data for each user you need thread_id like session id
    # config = {
    #     "configurable": {
    #         "thread_id": "user_vikas"
    #     }
    # }
    # every run starts fresh. for dynamic thread id
    import uuid
    config = {
        "configurable": {
            "thread_id": str(uuid.uuid4())
        }
    }

#for getting input from terminal
    user_input = input("Enter travel request: ")

    result = app.invoke(
        {
            "messages": [
                HumanMessage(content=user_input)
            ],
            "user_query": user_input,
            "flight_results": "",
            "hotel_results": "",
            "itinerary": "",
            "llm_calls": 0
        },
        config=config
    )

    print("\nFINAL RESPONSE:\n")

    for msg in result["messages"]:
        print(msg.content)